### PR TITLE
Make duplicate checking less restrictive by adding age checking

### LINKED ISSUE #195: [PE-D][Tester C] Cannot add two students with the same name even when all other details differ
## Summary
The app blocks adding a second student if the name is identical to an existing student, even when the rest of the details are different. In real usage, different students can share the same full name.

## Type and Severity
- type.FeatureFlaw
- severity.Medium

## Environment
- Platform: Windows
- App: CareContacts v1.5

## Steps to Reproduce
1. Launch CareContacts.
2. Add the first student:
   add n/Alex Tan a/10 ad/Blk 1 Test Road pn/Parent One pc/90000001 pe/parent1@gmail.com
3. Add another student with the same name but different details:
   add n/Alex Tan a/12 ad/Blk 2 Test Road pn/Parent Two pc/90000002 pe/parent2@gmail.com
4. Observe the command result.

## Expected
Both students should be allowed, since they represent different individuals with different contact information.

## Actual
The second add is rejected as a duplicate person.

## Why This Is a Problem
For student care workflows, duplicate names are common. Preventing same-name entries can force staff to store inaccurate names or lose records, which harms correctness and traceability.

## Screenshot
Image

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #209: [PE-D][Tester B] Duplicate handling for person may be too restrictive
Currently, two persons are considered duplicate if they have the same name. While user can work around by using different capitalisation or spacing, this might be too restrictive. Possible to consider same name and parent name instead.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by Annazx**
Two students are considered duplicates only if their names are exact matches (john doe and John  Doe are still considered different names) and their ages are the same. A warning is still shown if the user adds a student with the exact same name but different age along with a list of similar persons.

### Instructions for testing
1. Enter the command `add n\John Doe a\11 ....`
2. Enter the command `add n\John Doe a\7....`
Expected: John Doe aged 7 is added. A duplicate warning is shown in the message bar. A list of similar persons including John Doe aged 11 is shown.

I'm wondering if this would still be considered too restrictive. One of the testers suggested checking by parent name, but I don't think that's a very good idea as students can have multiple parents lol.

Closes #209 
Closes #195

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -116,7 +116,8 @@ public boolean isSamePerson(Person otherPerson) {
         }
 
         return otherPerson != null
-                && otherPerson.getName().equals(getName());
+                && otherPerson.getName().equals(getName())
+                && otherPerson.getAge().equals(getAge());
```
Comment (kah-seng) [inline src/main/java/seedu/address/model/person/Person.java:120]:
```suggestion
                && otherPerson.getName().equals(getName())
                && otherPerson.getAge().equals(getAge())
                && otherPerson.getParentName().equals(getParentName());
```

Should we also check against the parent's name?

**Review by kah-seng — APPROVED** [review]
LGTM, just a small suggestion

File: src/main/java/seedu/address/model/person/Person.java (hunk 1 above)
Comment (Annazx) [reply src/main/java/seedu/address/model/person/Person.java:120]: Hey, thanks for the suggestion! I agree that the current implementation (checking by name and age alone) might be too restrictive, but considering our NFR of 200 students, it seems unlikely that two students would have the exact same full name and age. Considering that many students have two parents and we don't check for parent name normalization, it could allow some possible duplicates to slip through.
